# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, conint


class AdvanceMarketRequest(BaseModel):
    event: str = Field(
        ...,
        description='Lifecycle event name, e.g. `go_live`, `enter_close_window`, `close`.',
    )


class ApiError(BaseModel):
    code: str
    message: str


class AuditActionDto(BaseModel):
    action: str
    actor_role: str
    actor_token_digest: str
    at: AwareDatetime
    id: UUID
    reason: str | None = None
    subject: str


class AuditPageDto(BaseModel):
    actions: list[AuditActionDto]
    next_before: AwareDatetime | None = None


class CommentDto(BaseModel):
    author_handle: str
    author_id: UUID
    body: str
    created_at: AwareDatetime
    depth: conint(ge=0)
    id: UUID
    market_id: UUID
    moderation_status: str
    parent_id: UUID | None = None
    reply_count: conint(ge=0)
    score: int


class CommentPageDto(BaseModel):
    comments: list[CommentDto]
    next_cursor: str | None = None


class CommentReportDto(BaseModel):
    report_count: conint(ge=0)
    reported: bool


class CommentVoteDto(BaseModel):
    score: int


class ConfigAppliedDto(BaseModel):
    changed_keys: list[str]
    generation: int


class ConfigEntryDto(BaseModel):
    key: str
    value: Any


class ConfigProposalDto(BaseModel):
    base_generation: int
    expires_at: AwareDatetime
    id: UUID
    patch: Any
    reason: str
    resulting_generation: int | None = None
    status: str


class ConfigSnapshotDto(BaseModel):
    entries: list[ConfigEntryDto]
    generation: int


class CreateConfigProposalRequest(BaseModel):
    idempotency_key: str
    patch: Any | None = None
    reason: str
    revert_of_generation: int | None = None


class CreateUserRequest(BaseModel):
    address: str
    channel: str
    created_at_override: AwareDatetime | None = None
    handle: str
    rep_seed_micro: int | None = None


class CuratorDecisionDto(Enum):
    resolve_at_tally = 'resolve_at_tally'
    void = 'void'


class DailyFeeRowDto(BaseModel):
    day: str
    payout_dust_micro: int
    total_micro: int
    trade_fee_micro: int


class DecideRequestDto(BaseModel):
    reason: str | None = None


class DepositAdmissionDto(BaseModel):
    collected_micro: int
    deposit_id: UUID
    ledger_txn: UUID | None = None
    replayed: bool


class DepositRefundDto(BaseModel):
    deposit_id: UUID
    dest: str
    payment_id: UUID
    replayed: bool


class DraftSourceDto(Enum):
    template = 'template'
    llm = 'llm'


class DraftTierDto(Enum):
    daily = 'daily'
    flash = 'flash'


class DualControlBody(BaseModel):
    reason: str


class DualControlRequest(BaseModel):
    idempotency_key: str
    reason: str


class FaucetDepositDto(BaseModel):
    amount_micro: int
    ledger_txn: UUID | None = Field(
        None,
        description='`None` on a replay observed through a different idempotency key.',
    )
    replayed: bool
    user_id: UUID


class FaucetDepositRequest(BaseModel):
    amount_micro: int
    idempotency_key: str
    reason: str
    user_id: UUID


class HolderDto(BaseModel):
    cost_micro: int = Field(
        ..., description='Ranked by committed capital; not mark-to-market value.'
    )
    handle: str
    tier: conint(ge=0)
    user_id: UUID


class HoldersDto(BaseModel):
    no: list[HolderDto]
    yes: list[HolderDto]


class IntegrityReportDto(BaseModel):
    checks: Any
    created_at: AwareDatetime
    verdict: str


class InvariantIdentityDto(BaseModel):
    detail: str | None = None
    identity: str
    pass_: bool = Field(..., alias='pass')


class InvariantReportDto(BaseModel):
    as_of: AwareDatetime
    identities: list[InvariantIdentityDto]
    pass_: bool = Field(..., alias='pass')


class MarkNotificationsReadRequest(BaseModel):
    ids: list[int]


class MarketStateDto(Enum):
    draft = 'draft'
    scheduled = 'scheduled'
    live = 'live'
    closing = 'closing'
    closed = 'closed'
    resolving = 'resolving'
    resolved = 'resolved'
    paid = 'paid'
    voided = 'voided'


class MarketSummaryDto(BaseModel):
    closes_at: AwareDatetime
    id: UUID
    no_outcome_id: UUID
    poster_asset_url: str | None = None
    price_no_micro: int
    price_yes_micro: int
    question: str
    server_now: AwareDatetime | None = None
    slug: str
    state: MarketStateDto
    tally_hidden_at: AwareDatetime
    tally_no: int | None = None
    tally_yes: int | None = None
    under_review: bool
    video_asset_url: str | None = None
    yes_outcome_id: UUID


class MarketUnwindDto(BaseModel):
    confirm_not_before: AwareDatetime
    market_id: UUID
    reason: str
    reversal_txn: UUID | None = None
    stage: str


class ModerateCommentRequest(BaseModel):
    status: str


class ModeratedCommentDto(BaseModel):
    status: str


class NotificationDto(BaseModel):
    created_at: AwareDatetime
    id: int
    market_id: UUID | None = None
    payload: Any
    read_at: AwareDatetime | None = None
    source_seq: int | None = None
    type: str


class NotificationPageDto(BaseModel):
    notifications: list[NotificationDto]
    unread_count: conint(ge=0)


class PostCommentRequest(BaseModel):
    body: str
    idempotency_key: str
    parent_id: UUID | None = None
    user_id: UUID


class PricePointDto(BaseModel):
    avg_price_micro: int
    bucket_start: AwareDatetime
    trades: conint(ge=0)
    volume_micro: int


class ProposalDto(BaseModel):
    confirm_not_before: AwareDatetime
    id: UUID
    kind: str
    status: str


class PublishDraftDto(BaseModel):
    draft_id: UUID
    market_id: UUID
    replayed: bool


class PublishStatusDto(BaseModel):
    draft_id: UUID
    error: str | None = None
    result_market_id: UUID | None = None
    status: str
    status_url: str = Field(
        ...,
        description='Poll here (also returned by the 202 publish-now authorization).',
    )


class ReceivableWriteOffDto(BaseModel):
    amount_micro: int
    receivable_id: UUID
    status: str


class RemedialCreditDto(BaseModel):
    amount_micro: int
    market_id: UUID
    status: str
    user_id: UUID


class RemedialCreditRequest(BaseModel):
    amount_micro: int
    idempotency_key: str
    reason: str
    user_id: UUID


class ReportCommentRequest(BaseModel):
    user_id: UUID


class ReportedCommentDto(BaseModel):
    comment: CommentDto
    report_count: conint(ge=0)
    reporters: list[str]


class ResolveMarketDto(BaseModel):
    actual_yes_bps: conint(ge=0) | None = None
    ledger_txn: UUID | None = None
    market_id: UUID
    replayed: bool
    state: MarketStateDto
    voided: bool


class ResolveMarketRequest(BaseModel):
    decision: CuratorDecisionDto


class ReviewDraftRequest(BaseModel):
    reviewer_id: UUID


class SetConfigRequest(BaseModel):
    expected_base_generation: int | None = Field(
        None, description='Optimistic base; a moved generation is a typed conflict.'
    )
    idempotency_key: str
    patch: Any = Field(..., description='Map of key → new value.')
    reason: str


class SettleConfigProposalRequest(BaseModel):
    reason: str | None = None


class SideDto(Enum):
    yes = 'yes'
    no = 'no'


class TradeActionDto(Enum):
    buy = 'buy'
    sell = 'sell'


class TradePreviewDto(BaseModel):
    action: TradeActionDto
    avg_price_micro: int
    config_version: int = Field(
        ...,
        description='Config generation this preview quoted against (D25a). Echo it back\nas `expected_config_version` when placing the trade.',
    )
    fee_micro: int
    gross_micro: int
    market_id: UUID
    shares_micro: int
    side: SideDto


class TradeReceiptDto(BaseModel):
    action: TradeActionDto
    avg_price_micro: int
    fee_micro: int
    gross_micro: int
    ledger_txn: UUID
    replayed: bool
    shares_micro: int
    side: SideDto
    trade_id: UUID


class TraderRowDto(BaseModel):
    handle: str
    realizations: conint(ge=0)
    realized_pnl_micro: int


class UnreadCountDto(BaseModel):
    unread_count: conint(ge=0)


class UpdatedDto(BaseModel):
    updated: conint(ge=0)


class UserIdDto(BaseModel):
    user_id: UUID


class VoteCommentRequest(BaseModel):
    idempotency_key: str
    user_id: UUID
    value: int


class VoteReceiptDto(BaseModel):
    crowd_guess_pct: conint(ge=0)
    market_id: UUID
    replayed: bool
    seq: int | None = None
    side: SideDto
    vote_id: UUID


class VoterRowDto(BaseModel):
    avg_score_bp: int
    handle: str
    markets_scored: conint(ge=0)
    tier: conint(ge=0)


class VoterSummaryDto(BaseModel):
    avg_score_bp: int | None = None
    markets_scored: conint(ge=0)


class WithdrawRequestDto(BaseModel):
    amount_micro: int
    confirm_dest: str = Field(
        ...,
        description='Required second entry of the destination; both values must canonicalize identically.',
    )
    dest: str
    idempotency_key: str | None = None
    user_id: UUID


class WithdrawalDecisionDto(BaseModel):
    combo: str
    id: UUID


class WithdrawalEligibilityDto(BaseModel):
    cash_micro: int
    eligible: bool
    open_receivables_micro: int
    user_id: UUID


class WithdrawalReceiptDto(BaseModel):
    amount_micro: int
    combo: str | None = None
    dest: str
    hold_tx_id: UUID | None = None
    id: UUID | None = None
    refuse_code: str | None = None
    refuse_message: str | None = None
    refused: bool
    replayed: bool
    user_id: UUID


class CastVoteRequest(BaseModel):
    crowd_guess_pct: conint(ge=0)
    idempotency_key: str
    market_ref: str
    run_id: UUID | None = None
    side: SideDto
    user_id: UUID


class CreateDraftRequest(BaseModel):
    allow_fallback: bool | None = None
    source: DraftSourceDto
    tier: DraftTierDto
    topics: list[str]


class DraftSpecDto(BaseModel):
    description: str
    fee_bps: conint(ge=0)
    hidden_window_secs: conint(ge=0)
    min_votes_to_resolve: int
    open_secs: conint(ge=0)
    question: str
    seed_micro: int
    slug: str
    tier: DraftTierDto
    video_script: str


class EditDraftRequest(BaseModel):
    reviewer_id: UUID
    spec: DraftSpecDto


class FlaggedMarketDto(BaseModel):
    curator_flagged_at: AwareDatetime | None = None
    integrity_due_at: AwareDatetime | None = None
    market_id: UUID
    question: str
    report: IntegrityReportDto | None = None
    slug: str
    state: MarketStateDto


class MarketAdvancedDto(BaseModel):
    from_state: MarketStateDto
    market_id: UUID
    state: MarketStateDto


class PlaceTradeRequest(BaseModel):
    action: TradeActionDto
    amount_micro: int
    expected_config_version: int = Field(
        ..., description="The preview's `config_version` echo (D36: required)."
    )
    idempotency_key: str
    market_ref: str
    pending_action_id: UUID | None = None
    run_id: UUID | None = None
    side: SideDto
    user_id: UUID


class PositionDto(BaseModel):
    cost_micro: int
    market_id: UUID
    outcome_id: UUID
    realized_pnl_micro: int
    rep_micro: int
    shares_micro: int
    side: SideDto
    tier: conint(ge=0)


class PreviewTradeRequest(BaseModel):
    action: TradeActionDto
    amount_micro: int
    market_ref: str
    side: SideDto
    user_id: UUID


class ProfileTradeDto(BaseModel):
    action: TradeActionDto
    collateral_micro: int
    created_at: AwareDatetime
    market_id: UUID
    market_ref: str
    side: SideDto
    trade_seq: int


class ProfileVoteDto(BaseModel):
    cast_at: AwareDatetime
    market_id: UUID
    market_question: str
    score_bp: conint(ge=0) | None = None
    side: SideDto | None = None


class TapeRowDto(BaseModel):
    action: TradeActionDto
    collateral_micro: int
    created_at: AwareDatetime
    handle: str
    side: SideDto
    trade_seq: int


class UserProfileDto(BaseModel):
    created_at: AwareDatetime
    handle: str
    realized_pnl_micro: int
    recent_trades: list[ProfileTradeDto]
    recent_votes: list[ProfileVoteDto]
    rep_micro: int
    tier: conint(ge=0)
    user_id: UUID
    voter: VoterSummaryDto


class DraftDto(BaseModel):
    created_at: AwareDatetime
    expires_at: AwareDatetime
    fallback_from: DraftSourceDto | None = None
    id: UUID
    publish_at: AwareDatetime | None = None
    publish_stage: str | None = None
    published_market_id: UUID | None = None
    source: DraftSourceDto
    spec: DraftSpecDto
    status: str
