# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, conint


class AdvanceMarketRequest(BaseModel):
    event: str = Field(
        ...,
        description='Lifecycle event name, e.g. `go_live`, `enter_close_window`, `close`.',
    )


class ApiError(BaseModel):
    code: str
    message: str


class AuditActionDto(BaseModel):
    action: str
    actor_role: str
    actor_token_digest: str
    at: datetime
    id: UUID
    reason: Optional[str] = None
    subject: str


class AuditPageDto(BaseModel):
    actions: List[AuditActionDto]
    next_before: Optional[datetime] = None


class CommentDto(BaseModel):
    author_handle: str
    author_id: UUID
    body: str
    created_at: datetime
    depth: conint(ge=0)
    id: UUID
    market_id: UUID
    moderation_status: str
    parent_id: Optional[UUID] = None
    reply_count: conint(ge=0)
    score: int


class CommentPageDto(BaseModel):
    comments: List[CommentDto]
    next_cursor: Optional[str] = None


class CommentReportDto(BaseModel):
    report_count: conint(ge=0)
    reported: bool


class CommentVoteDto(BaseModel):
    score: int


class ConfigAppliedDto(BaseModel):
    changed_keys: List[str]
    generation: int


class ConfigEntryDto(BaseModel):
    key: str
    value: Any


class ConfigProposalDto(BaseModel):
    base_generation: int
    expires_at: datetime
    id: UUID
    patch: Any
    reason: str
    resulting_generation: Optional[int] = None
    status: str


class ConfigSnapshotDto(BaseModel):
    entries: List[ConfigEntryDto]
    generation: int


class CreateConfigProposalRequest(BaseModel):
    idempotency_key: str
    patch: Optional[Any] = None
    reason: str
    revert_of_generation: Optional[int] = None


class CreateUserRequest(BaseModel):
    address: str
    channel: str
    created_at_override: Optional[datetime] = None
    handle: str
    rep_seed_micro: Optional[int] = None


class CuratorDecisionDto(Enum):
    resolve_at_tally = 'resolve_at_tally'
    void = 'void'


class DailyFeeRowDto(BaseModel):
    day: str
    payout_dust_micro: int
    total_micro: int
    trade_fee_micro: int


class DraftSourceDto(Enum):
    template = 'template'
    llm = 'llm'


class DraftTierDto(Enum):
    daily = 'daily'
    flash = 'flash'


class DualControlRequest(BaseModel):
    idempotency_key: str
    reason: str


class FaucetDepositDto(BaseModel):
    amount_micro: int
    ledger_txn: Optional[UUID] = Field(
        None,
        description='`None` on a replay observed through a different idempotency key.',
    )
    replayed: bool
    user_id: UUID


class FaucetDepositRequest(BaseModel):
    amount_micro: int
    idempotency_key: str
    reason: str
    user_id: UUID


class HolderDto(BaseModel):
    cost_micro: int = Field(
        ..., description='Ranked by committed capital; not mark-to-market value.'
    )
    handle: str
    tier: conint(ge=0)
    user_id: UUID


class HoldersDto(BaseModel):
    no: List[HolderDto]
    yes: List[HolderDto]


class IntegrityReportDto(BaseModel):
    checks: Any
    created_at: datetime
    verdict: str


class InvariantIdentityDto(BaseModel):
    detail: Optional[str] = None
    identity: str
    pass_: bool = Field(..., alias='pass')


class InvariantReportDto(BaseModel):
    as_of: datetime
    identities: List[InvariantIdentityDto]
    pass_: bool = Field(..., alias='pass')


class MarkNotificationsReadRequest(BaseModel):
    ids: List[int]


class MarketStateDto(Enum):
    draft = 'draft'
    scheduled = 'scheduled'
    live = 'live'
    closing = 'closing'
    closed = 'closed'
    resolving = 'resolving'
    resolved = 'resolved'
    paid = 'paid'
    voided = 'voided'


class MarketSummaryDto(BaseModel):
    closes_at: datetime
    id: UUID
    no_outcome_id: UUID
    poster_asset_url: Optional[str] = None
    price_no_micro: int
    price_yes_micro: int
    question: str
    server_now: Optional[datetime] = None
    slug: str
    state: MarketStateDto
    tally_hidden_at: datetime
    tally_no: Optional[int] = None
    tally_yes: Optional[int] = None
    under_review: bool
    video_asset_url: Optional[str] = None
    yes_outcome_id: UUID


class MarketUnwindDto(BaseModel):
    confirm_not_before: datetime
    market_id: UUID
    reason: str
    reversal_txn: Optional[UUID] = None
    stage: str


class ModerateCommentRequest(BaseModel):
    status: str


class ModeratedCommentDto(BaseModel):
    status: str


class NotificationDto(BaseModel):
    created_at: datetime
    id: int
    market_id: Optional[UUID] = None
    payload: Any
    read_at: Optional[datetime] = None
    source_seq: Optional[int] = None
    type: str


class NotificationPageDto(BaseModel):
    notifications: List[NotificationDto]
    unread_count: conint(ge=0)


class PostCommentRequest(BaseModel):
    body: str
    idempotency_key: str
    parent_id: Optional[UUID] = None
    user_id: UUID


class PricePointDto(BaseModel):
    avg_price_micro: int
    bucket_start: datetime
    trades: conint(ge=0)
    volume_micro: int


class PublishDraftDto(BaseModel):
    draft_id: UUID
    market_id: UUID
    replayed: bool


class PublishStatusDto(BaseModel):
    draft_id: UUID
    error: Optional[str] = None
    result_market_id: Optional[UUID] = None
    status: str
    status_url: str = Field(
        ...,
        description='Poll here (also returned by the 202 publish-now authorization).',
    )


class ReceivableWriteOffDto(BaseModel):
    amount_micro: int
    receivable_id: UUID
    status: str


class RemedialCreditDto(BaseModel):
    amount_micro: int
    market_id: UUID
    status: str
    user_id: UUID


class RemedialCreditRequest(BaseModel):
    amount_micro: int
    idempotency_key: str
    reason: str
    user_id: UUID


class ReportCommentRequest(BaseModel):
    user_id: UUID


class ReportedCommentDto(BaseModel):
    comment: CommentDto
    report_count: conint(ge=0)
    reporters: List[str]


class ResolveMarketDto(BaseModel):
    actual_yes_bps: Optional[conint(ge=0)] = None
    ledger_txn: Optional[UUID] = None
    market_id: UUID
    replayed: bool
    state: MarketStateDto
    voided: bool


class ResolveMarketRequest(BaseModel):
    decision: CuratorDecisionDto


class ReviewDraftRequest(BaseModel):
    reviewer_id: UUID


class SetConfigRequest(BaseModel):
    expected_base_generation: Optional[int] = Field(
        None, description='Optimistic base; a moved generation is a typed conflict.'
    )
    idempotency_key: str
    patch: Any = Field(..., description='Map of key → new value.')
    reason: str


class SettleConfigProposalRequest(BaseModel):
    reason: Optional[str] = None


class SideDto(Enum):
    yes = 'yes'
    no = 'no'


class TradeActionDto(Enum):
    buy = 'buy'
    sell = 'sell'


class TradePreviewDto(BaseModel):
    action: TradeActionDto
    avg_price_micro: int
    config_version: int = Field(
        ...,
        description='Config generation this preview quoted against (D25a). Echo it back\nas `expected_config_version` when placing the trade.',
    )
    fee_micro: int
    gross_micro: int
    market_id: UUID
    shares_micro: int
    side: SideDto


class TradeReceiptDto(BaseModel):
    action: TradeActionDto
    avg_price_micro: int
    fee_micro: int
    gross_micro: int
    ledger_txn: UUID
    replayed: bool
    shares_micro: int
    side: SideDto
    trade_id: UUID


class TraderRowDto(BaseModel):
    handle: str
    realizations: conint(ge=0)
    realized_pnl_micro: int


class UnreadCountDto(BaseModel):
    unread_count: conint(ge=0)


class UpdatedDto(BaseModel):
    updated: conint(ge=0)


class UserIdDto(BaseModel):
    user_id: UUID


class VoteCommentRequest(BaseModel):
    idempotency_key: str
    user_id: UUID
    value: int


class VoteReceiptDto(BaseModel):
    crowd_guess_pct: conint(ge=0)
    market_id: UUID
    replayed: bool
    seq: Optional[int] = None
    side: SideDto
    vote_id: UUID


class VoterRowDto(BaseModel):
    avg_score_bp: int
    handle: str
    markets_scored: conint(ge=0)
    tier: conint(ge=0)


class VoterSummaryDto(BaseModel):
    avg_score_bp: Optional[int] = None
    markets_scored: conint(ge=0)


class WithdrawalEligibilityDto(BaseModel):
    cash_micro: int
    eligible: bool
    open_receivables_micro: int
    user_id: UUID


class CastVoteRequest(BaseModel):
    crowd_guess_pct: conint(ge=0)
    idempotency_key: str
    market_ref: str
    run_id: Optional[UUID] = None
    side: SideDto
    user_id: UUID


class CreateDraftRequest(BaseModel):
    allow_fallback: Optional[bool] = None
    source: DraftSourceDto
    tier: DraftTierDto
    topics: List[str]


class DraftSpecDto(BaseModel):
    description: str
    fee_bps: conint(ge=0)
    hidden_window_secs: conint(ge=0)
    min_votes_to_resolve: int
    open_secs: conint(ge=0)
    question: str
    seed_micro: int
    slug: str
    tier: DraftTierDto
    video_script: str


class EditDraftRequest(BaseModel):
    reviewer_id: UUID
    spec: DraftSpecDto


class FlaggedMarketDto(BaseModel):
    curator_flagged_at: Optional[datetime] = None
    integrity_due_at: Optional[datetime] = None
    market_id: UUID
    question: str
    report: Optional[IntegrityReportDto] = None
    slug: str
    state: MarketStateDto


class MarketAdvancedDto(BaseModel):
    from_state: MarketStateDto
    market_id: UUID
    state: MarketStateDto


class PlaceTradeRequest(BaseModel):
    action: TradeActionDto
    amount_micro: int
    expected_config_version: int = Field(
        ..., description="The preview's `config_version` echo (D36: required)."
    )
    idempotency_key: str
    market_ref: str
    pending_action_id: Optional[UUID] = None
    run_id: Optional[UUID] = None
    side: SideDto
    user_id: UUID


class PositionDto(BaseModel):
    cost_micro: int
    market_id: UUID
    outcome_id: UUID
    realized_pnl_micro: int
    rep_micro: int
    shares_micro: int
    side: SideDto
    tier: conint(ge=0)


class PreviewTradeRequest(BaseModel):
    action: TradeActionDto
    amount_micro: int
    market_ref: str
    side: SideDto
    user_id: UUID


class ProfileTradeDto(BaseModel):
    action: TradeActionDto
    collateral_micro: int
    created_at: datetime
    market_id: UUID
    market_ref: str
    side: SideDto
    trade_seq: int


class ProfileVoteDto(BaseModel):
    cast_at: datetime
    market_id: UUID
    market_question: str
    score_bp: Optional[conint(ge=0)] = None
    side: Optional[SideDto] = None


class TapeRowDto(BaseModel):
    action: TradeActionDto
    collateral_micro: int
    created_at: datetime
    handle: str
    side: SideDto
    trade_seq: int


class UserProfileDto(BaseModel):
    created_at: datetime
    handle: str
    realized_pnl_micro: int
    recent_trades: List[ProfileTradeDto]
    recent_votes: List[ProfileVoteDto]
    rep_micro: int
    tier: conint(ge=0)
    user_id: UUID
    voter: VoterSummaryDto


class DraftDto(BaseModel):
    created_at: datetime
    expires_at: datetime
    fallback_from: Optional[DraftSourceDto] = None
    id: UUID
    publish_at: Optional[datetime] = None
    publish_stage: Optional[str] = None
    published_market_id: Optional[UUID] = None
    source: DraftSourceDto
    spec: DraftSpecDto
    status: str
